jobs:
  build:
    if: github.repository == 'mirromutth/r2dbc-mysql'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Temurin 8
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Initialize Maven Version
      run: ./mvnw -q org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version
    - continue-on-error: true
      name: Set up GPG
      run: 'mkdir -m 700 -p ~/.gnupg

        install -m 600 <(echo "${{ secrets.GPG_SECRING_ENCODED }}") ~/.gnupg/secring.gpg.b64

        install -m 600 <(base64 -d ~/.gnupg/secring.gpg.b64) ~/.gnupg/secring.gpg

        gpg -k

        '
    - continue-on-error: true
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      name: Release with Maven
      run: ./ci/central.sh
    - continue-on-error: true
      name: Clean up GPG
      run: rm -rf ~/.gnupg
name: Stage release to Maven Central
on:
  repository_dispatch:
    types: trigger-ga___deploy-release.yml
