jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Temurin 8
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Shutdown the Default MySQL
      run: sudo service mysql stop
    - continue-on-error: true
      name: Set up MySQL 8.0
      uses: mirromutth/mysql-action@v1.1
      with:
        collation server: utf8mb4_0900_ai_ci
        mysql database: r2dbc
        mysql root password: ${{ secrets.DB_PASSWORD }}
        mysql version: 8.0
    - continue-on-error: true
      name: Integration test with MySQL 8.0
      run: ./mvnw -B verify -Dmaven.javadoc.skip=true -Dmaven.surefire.skip=true -Dtest.mysql.password=${{
        secrets.DB_PASSWORD }} -Dtest.mysql.version=8.0 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
name: MySQL 8.0
on:
  repository_dispatch:
    types: trigger-ga___mysql8-0.yml
