jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Temurin 8
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Unit test with Maven
      run: ./mvnw -B test -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
name: Unit tests
on:
  repository_dispatch:
    types: trigger-ga___unit-tests.yml
